<!--
  ~ Copyright (c) 2026 MirraNET, Niklas Linz. All rights reserved.
  ~
  ~ This file is part of the MirraNET project and is licensed under the
  ~ GNU Lesser General Public License v3.0 (LGPLv3).
  ~
  ~ You may use, distribute and modify this code under the terms
  ~ of the LGPLv3 license. You should have received a copy of the
  ~ license along with this file. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>
  ~ or contact: niklas.linz@mirranet.de
  -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>de.linzn</groupId>
    <packaging>jar</packaging>
    <name>STEM</name>
    <version>${version.versionNumber}-${version.buildLabel}</version>
    <artifactId>stem</artifactId>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <version.versionNumber>1.1.0</version.versionNumber>
        <version.buildNumber>CUSTOM</version.buildNumber>
        <version.buildLabel>SNAPSHOT</version.buildLabel>
    </properties>
    <repositories>
        <repository>
            <id>mvnrepository</id>
            <name>mvnrepository</name>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
        <repository>
            <id>Eclipse Paho Repo</id>
            <url>https://repo.eclipse.org/content/repositories/paho-releases/</url>
        </repository>
        <repository>
            <id>MirraNET Repository</id>
            <url>https://builds.mirranet.de/plugin/repository/everything/</url>
        </repository>
    </repositories>

    <build>
        <resources>
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
                <includes>
                    <include>**</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>de.linzn.stem.STEMApp</mainClass>
                            <classpathPrefix>core/dependencies</classpathPrefix>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.0</version>
                <configuration>
                    <source>25</source>
                    <target>25</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>process-sources</phase>

                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>

                        <configuration>
                            <outputDirectory>target/core/dependencies</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <archiveClasses>true</archiveClasses>
                </configuration>
            </plugin>

        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>12.1.5</version>
        </dependency>
        <dependency>
            <groupId>de.linzn</groupId>
            <artifactId>stemLink</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>de.linzn</groupId>
            <artifactId>openJL</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.5.0-jre</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20251224</version>
        </dependency>
        <dependency>
            <groupId>org.xerial</groupId>
            <artifactId>sqlite-jdbc</artifactId>
            <version>3.51.1.0</version>
        </dependency>
        <dependency>
            <groupId>it.sauronsoftware.cron4j</groupId>
            <artifactId>cron4j</artifactId>
            <version>2.2.5</version>
        </dependency>
        <dependency>
            <groupId>de.linzn</groupId>
            <artifactId>simplyConfiguration</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>de.linzn</groupId>
            <artifactId>simplyDatabase</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>de.linzn</groupId>
            <artifactId>simplyLogger</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.2.5</version>
        </dependency>
        <dependency>
            <groupId>org.aarboard.nextcloud</groupId>
            <artifactId>nextcloud-api</artifactId>
            <version>14.1.0</version>
        </dependency>
    </dependencies>
</project>